---
- name: Passwordless login by root account & System host entry updates
  hosts: kubernetes-master-nodes
  name: Generate ssh key for root account
  tasks:
    - name: Generate ssh key for root
      shell: > 
        ssh-keygen -q -b 2048 -t rsa -N "" -C "root" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"

- hosts: kubernetes-worker-nodes
  tasks:
    - name: Create SSH key directory on worker nodes
      file: 
        path: /root/.ssh
        state: directory
    
    - name: Transfer SSH key files to worker nodes 
      copy:
        src: "~/.ssh/id_rsa.pub"
        dest: "~/.ssh/authorized_keys"
        mode: '0600'

- hosts: kubernetes-worker-nodes
  name: Transfer host name updates from master node to worker nodes
  tasks:
    - name: Host entry dummy file
      copy:
        src: /tmp/dummy_host_entries2
        dest: /tmp/dummy_host_entries2

    - name: host entri update
      shell: |
        cat /tmp/dummy_host_entries2 >> /etc/hosts
        cat /etc/hosts | sort | uniq > /tmp/host_dummy_entries
        cat /tmp/host_dummy_entries > /etc/hosts
 
